{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ include "external-dns.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.serviceAccount.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
{{- end }}
