global:
  licenseKey: "REPLACE_WITH_YOUR_NEW_RELIC_LICENSE_KEY"
  cluster: "amazon-dev-eks"
  lowDataMode: false

newrelic-infrastructure:
  enabled: true
  privileged: true

kube-state-metrics:
  enabled: true

prometheus:
  enabled: false

grafana:
  enabled: false
